export const enum NetworkType {
  AEM_ENTITY = 'AEM_ENTITY',

  AEM_RESIDENCE = 'AEM_RESIDENCE',

  AEM_SAAD = 'AEM_SAAD',

  AEM_SSIAD = 'AEM_SSIAD',

  AEM_NEWS = 'AEM_NEWS',

  AEM_ANIMATION = 'AEM_ANIMATION',

  AEM_FAMILY = 'AEM_FAMILY',

  AEM_COMMUNITY = 'AEM_COMMUNITY',

  AEM_COORDINATION = 'AEM_COORDINATION',

  UNKNOWN = 'UNKNOWN',
}
